### ISSUE TITLE
Broken link in HSP90 cookbook

### ISSUE THREAD

**Issue by mattwthompson** [openmm/openmm-org#104]
https://github.com/openmm/openmm-org/blob/483b83410ab972f80caf20032d17fbb38d3bc1f1/tutorials_/hsp90_adp_mg/index.md?plain=1#L15C363-L15C413

https://septlab.engin.umich.edu/multisite-ions.html

<img width="1188" alt="image" src="https://github.com/user-attachments/assets/195de186-717d-4beb-b748-71900a434db2">

**Comment by peastman** [comment]
It looks like this is probably the correct link?  https://septlab.engin.umich.edu/multisite-divalent-cation-models/

**Comment by mattwthompson** [comment]
I see a big and messy `tleap` blob, so looks correct to me
