### ISSUE TITLE
Update to website?

### ISSUE THREAD

**Issue by peastman** [openmm/openmm-org#28]
I pushed some changes to the master branch yesterday, but they still don't seem to be showing up in the live website.  Is there something else I need to do?

**Comment by peastman** [comment]
@jchodera do you have any idea about this?  You were the last person to edit the deployment code, so I assume you have some idea how it works (unlike me!).  See the error log at https://travis-ci.org/pandegroup/openmm-org, which contains a huge stack trace but no information I'm sure how to interpret.

**Comment by jchodera** [comment]
Whoops, I wasn't watching this repo and hadn't seen this earlier!

That error looks like a timeout during transfer. [This issue](https://github.com/aws/aws-sdk-ruby/issues/904) suggests one cause could be caused by a misspecified availability zone, but it may not be the case if those earlier files get pushed in [these lines](https://travis-ci.org/pandegroup/openmm-org/jobs/470780273#L761-L768).

I've retriggered travis to see if it generates the same error.

**Comment by peastman** [comment]
Any updates on this?  I see the website is still showing the old benchmarks.

**Comment by jchodera** [comment]
Sorry about the delay---I've just been totally buried, but can get to it this weekend.

**Comment by peastman** [comment]
@jchodera I take it you didn't get to this that weekend? :)  But fixing this is now quite urgent.  We'll probably be releasing 7.4 next week, and if this still isn't fixed, we won't be able to update the website!

**Comment by jchodera** [comment]
Understood! Working on debugging.
We also need to put up some information about the OpenMM Consortium.

**Comment by jchodera** [comment]
@peastman : It looks like I don't have edit/write access to the https://github.com/pandegroup/openmm-org repo. Can you add me? I might have to edit the secret env vars.

Perhaps we should also migrate this to the http://github.com/openmm org at the same time?

**Comment by peastman** [comment]
I'll move this over to the openmm org.

**Comment by peastman** [comment]
You should have access now.

**Comment by jchodera** [comment]
Thanks!

**Comment by jchodera** [comment]
I'm still working through travis/S3 issues. Will probably take through the weekend.

**Comment by jchodera** [comment]
@peastman : The good news is that the docs for 7.4.0 were successfully pushed to http://docs.openmm.org, and are available in the http://docs.openmm.org/7.4.0 subdirectories, as in
* User guide: http://docs.openmm.org/7.4.0/userguide/index.html
* Dev guide: http://docs.openmm.org/7.4.0/developerguide/index.html
* Python API: http://docs.openmm.org/7.4.0/api-python/index.html
* C++ API: http://docs.openmm.org/7.4.0/api-c++/index.html

The 7.4.0 docs are not being pushed to the `latest` directory in the `docs.openmm.org` bucket, however. Do you recall if we had to do this manually?

It occurs to me we don't include the manual version number in the manual text---we may want to do that somehow!

We should also update the copyright:
> Portions copyright (c) 2008-2017 Stanford University and the Authors

**Comment by jchodera** [comment]
@peastman: It looks like we manually copy the docs into `latest`:
https://github.com/openmm/openmm/issues/1813
I'll see if I can figure out how to do it, but it would be cool if we could just push to `latest` at deploy time as well.

**Comment by jchodera** [comment]
@peastman: Also, I've verified the development docs are properly deployed from the http://github.com/openmm/openmm repo. 

What I haven't figured out is how the 7.4.0 release docs were pushed to the `docs.openmm.org` bucket. Any ideas?

**Comment by jchodera** [comment]
Correction: The User and Dev guide are properly deploying to the `development` docs, but not the Python or C++ API docs.

**Comment by peastman** [comment]
The 7.4 docs got uploaded because I manually uploaded them yesterday!  I believe we've always done that.  They don't involve this repository.  The development docs are supposed to automatically get uploaded by travis.

**Comment by jchodera** [comment]
@peastman: 

Good news: This repo is now correctly deploying.

Bad news: The [benchmarks page](http://openmm.org/about.html#benchmarks) is only updated for 7.3. Do we have 7.4 benchmarks?

**Comment by jchodera** [comment]
> The 7.4 docs got uploaded because I manually uploaded them yesterday! I believe we've always done that.

Great! You'll just need to do the same thing to upload them to `latest` in the `docs.openmm.org` bucket as well.

**Comment by peastman** [comment]
> The benchmarks page is only updated for 7.3. Do we have 7.4 benchmarks?

Not yet.  But that means https://github.com/openmm/openmm-org/pull/27 has finally gotten deployed, so I can start doing all the updates to the website for 7.4.
