### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm-org#38]
The openmm.org certificate has expired.

@peastman : Do you know anything about how SSL certificates work, or how to renew ours?

**Comment by peastman** [comment]
Very little, I'm afraid.  It isn't something I've ever had to deal with.

**Comment by Lnaden** [comment]
If the site is being hosted to an s3 bucket, than I suspect its also being served a certificate through [Amazon ACM](https://aws.amazon.com/certificate-manager/). So whoever has root or IAM access to the s3 and acm service should be able to just request a new cert.

That's just a guess though, I don't know how the certificate is actually managed.

**Comment by peastman** [comment]
That seems possible.  How do I determine whether that's what it's using?

Alternatively if we can [get it moved over to Github Pages](https://github.com/openmm/openmm/issues/2824) this won't be an issue anymore.

**Comment by Lnaden** [comment]
Good question. I don't actually know to be honest. My Chrome browser seems to think there is no certificate (or at least its not showing me one), even an expired one. 

There are a few guides I have found, they involve using the AWS CloudFront to post the cert after generating. Here is one 

https://thenewstack.io/how-to-set-up-your-s3-bucket-with-https-in-an-hour/

But... tacking on more services might add to the cost. It may be better to somehow serve the cert through another means. I think some google-fu of searching for things like "update s3 certificate" or some such stuff might give better answers than I can right now.

**Comment by Lnaden** [comment]
might also be able to get a 3rd party cert (e.g. lets-encrypt and certbot) and have the bucket just point to that. i'd have to see how buckets serve sites to tell though

**Comment by Lnaden** [comment]
If either of you have access to issue a new IAM to the aws group, I can take a look and see if I can figure out how the cert was set up, and document how to get a new one for next time this happens?

**Comment by raimis** [comment]
After the migration to GitHub Pages, we no longer need to care about the SSL certificates.
