### ISSUE TITLE
Priorities of improvements

### ISSUE THREAD

**Issue by raimis** [openmm/openmm-org#44]
@giadefa just made me the admin of this repository. So, I'll dedicate some of my time maintaining and improving http://openmm.org 

@jchodera @peastman First, I want to discuss what would be priorities. Are any specific issues I should start with?

In general, my opinion is that the navigation is a bit messy. There are 3 buttons at the top, 5 big links an the bottom, this should be organized into a single menu structure. Also, the home page is quite empty, probably we could add the code spinet from http://openmm.org/about.html and one of the embedded videos from http://openmm.org/documentation.html

**Comment by peastman** [comment]
Agreed about the navigation.  Do you want to put together a mockup of a revised version?

**Comment by raimis** [comment]
I have made a mock up of the new website: https://raimis.github.io/openmm-org/

- Navigation and layout are mostly done. Content is just copied from the old one.
- The site is completely static (from the server side). It could be hosted on GitHub Pages.
- Jekyll is too primitive even for a such simple site like this. So I have replaced it with Vue.

@jchodera @peastman @giadefa

**Comment by peastman** [comment]
I really like this design!  The organization is much clearer than before.

**Comment by giadefa** [comment]
I like it

**Comment by jchodera** [comment]
@raimis : Thanks so much for putting this together, @raimis! Let me get you more detailed feedback this weekend.

One major goal is to make the website easier to update and add content to. Is it still using jekyll through a PR somewhere I can inspect?

**Comment by raimis** [comment]
@jchodera 

PR: https://github.com/openmm/openmm-org/pull/45

As mentioned above, *Jekyll* was replaced by *Vue*.

For maintainability:
- Each tab is a separate component. So, it should be easy to find there to change, e.g. the documentation tab (https://github.com/raimis/openmm-org/blob/new/documentation.vue)
- Tutorials (formatting is still not cleaned up) are rendered directly from *Mardown* files (https://github.com/raimis/openmm-org/blob/new/tutorials.vue).
- Other data, such as benchmark numbers (https://github.com/raimis/openmm-org/blob/new/benchmarks.json), are fetched from a file and rendered on-the-fly.

**Comment by raimis** [comment]
@jchodera @peastman 

Regarding SimTK and Omnia, how much those are still relevant? Or they are just a legacy? I'm wondering how much emphasis to put on them in the new website?

Regarding the tutorial, apart the ones in this repo, I found this https://github.com/choderalab/openmm-tutorials. Are they still maintained? Maybe it would make sense to keep all the tutorials together?

**Comment by giadefa** [comment]
if possible I would remove them

**Comment by peastman** [comment]
The forum on simtk.org is still quite active, so we want to keep the link to that.  But otherwise, there doesn't need to be any simtk branding.

I don't think a lot has been done with the omnia brand in a while.

**Comment by giadefa** [comment]
What about moving the forum to github discussions in openmm directly?

**Comment by jchodera** [comment]
> What about moving the forum to github discussions in openmm directly?

I'd really like to migrate away from simtk to github, so think we should at least enable GitHub Discussions. See the docs [here](https://docs.github.com/en/discussions).

I wonder if there would be a way to work with GitHub to migrate the old SimTK forums (including datestamps) to GitHub at some point. I know there's a lot of history there that might make sense to preserve. 

Alternatively, we can just go through the forums and distill the learnings into a FAQ.

**Comment by jchodera** [comment]
> Regarding SimTK and Omnia, how much those are still relevant? Or they are just a legacy? I'm wondering how much emphasis to put on them in the new website?

I think we should remove references to Omnia at this point. We are now deploying through [Conda Forge](https://conda-forge.org/), which is our larger scientific app community now.

**Comment by jchodera** [comment]
@raimis : Thanks so much for tackling this, and your patience in letting us look through this! 

I think this is a big usability and maintainability improvement. Let us know how we can help provide useful information to populate it.

**Comment by raimis** [comment]
@jchodera @giadefa @peastman 

New website (#45): https://raimis.github.io/openmm-org/

Current status:
- Migrated most of the content from the old website
- Reorganised the content into several sections (tabs)
- Layout/formatting is done, but needs a bit of tweaking to look good

My plan is to finish fixing layout/formatting issues and replace the old website. Further improvements will come after.

I need your feedback! Regarding the design or content, is anything in particular need to be changed before?

**Comment by raimis** [comment]
The new website is done!
