### ISSUE TITLE
Adding wepy to the OpenMM ecosystem

### ISSUE THREAD

**Issue by salotz-sitx** [openmm/openmm-org#52]
I've been using OpenMM as the main MD engine inside of [wepy](https://github.com/ADicksonLab/wepy) for a few years now and it would be nice to have it added to the ecosystem page.
Let me know what else you want for it.

Here is the description:

> A Weighted Ensemble (WE) simulation framework in Python with first class support for OpenMM.

**Comment by raimis** [comment]
@salotz-sitx 

We are happy to mention wepy on the OpenMM website.

I just notice that the OpenMM installation instructions on the wepy website (https://adicksonlab.github.io/wepy/_source/installation.html) is outdated. Could you update the instruction or just reference to the relevant part of the OpenMM documentation.

**Comment by raimis** [comment]
Also, here: https://adicksonlab.github.io/wepy/_source/introduction.html#compatibility

**Comment by salotz** [comment]
I updated the documentation. Thank you @raimis

**Comment by raimis** [comment]
The link has been added.
