### ISSUE TITLE
Add NIH funding acknowledgment

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm-org#57]
Now that we are [NIH-supported](https://www.choderalab.org/news/openmm-nih-grant-awarded), we should add an acknowledgment to our NIH support and [NIH grant R01GM140090](https://reporter.nih.gov/search/XnJncpjxUkSKiIFzf9su9A/project-details/10100573).

**Comment by raimis** [comment]
What text should I put exactly?

**Comment by jchodera** [comment]
Here's the text:

# National Institutes of Health 

OpenMM is currently (July 2021 - Mar 2025) supported by the [National Institute of General Medical Sciences](https://www.nigms.nih.gov/) of the [National Institutes of Health](https://www.nih.gov/) under award number [R01GM140090](https://reporter.nih.gov/search/XnJncpjxUkSKiIFzf9su9A/project-details/10100573).

**Comment by raimis** [comment]
@jchodera 

Done: https://raimis.github.io/openmm-org/development

Any comments?

**Comment by jchodera** [comment]
Perfect! Thanks, @raimis!

**Comment by jchodera** [comment]
Fixed by #61
