### ISSUE TITLE
Benchmarks are missing

### ISSUE THREAD

**Issue by peastman** [openmm/openmm-org#59]
I just noticed that the benchmarks seem to be missing.  When I go to the Benchmarks tab it describes all the benchmarks we ran, but doesn't list any of the results.  I'm pretty sure they used to be there.  Something seems to have broken it.

**Comment by peastman** [comment]
Looking at the browser console, I see some error messages appear when I load that tab.  They don't make a lot of sense to me: it claims https://openmm.org/benchmarks returned a 404, but the page still displayed?  Just as a guess, perhaps Vue Router is getting confused about the difference between https://openmm.org/benchmarks and https://openmm.org/benchmarks.json?

**Comment by raimis** [comment]
The 404 error is intentional. It is a way to circumvent one limitation of GitHub pages (https://learnvue.co/2020/09/how-to-deploy-your-vue-app-to-github-pages/).

Yes, the benchmarks plot should be visible. I'll investigate!

**Comment by raimis** [comment]
Works again: https://openmm.org/benchmarks

**Comment by peastman** [comment]
Looks good, thanks!
