### ISSUE TITLE
Joint Amber/Charmm benchmark link for DHRF case does not work

### ISSUE THREAD

**Issue by synjon-symthe** [openmm/openmm-org#81]
The dihydrofolate reductase (DHFR) models benchmark (Joint Amber/Charmm benchmark) link on 
https://openmm.org/benchmarks
gives a page not found -404 error. (http://ambermd.org/amber10.bench1.html)

**Comment by raimis** [comment]
The links is updated (https://github.com/openmm/openmm-org/pull/83)
