### ISSUE TITLE
Update of the performance benchmarks

### ISSUE THREAD

**Issue by raimis** [openmm/openmm-org#84]
- The current performance benchmarks (https://openmm.org/benchmarks) are just for OpenMM 7.4 and missing the latest GPUs (Turing and Apere cards).
- Only DHFR is on the OpenMM website, while the rest are on the SimTK website (https://simtk.org/plugins/moinmoin/openmm/Benchmarks).

**Comment by peastman** [comment]
I've been meaning to update them.  I reran most of the benchmarks (the updated numbers are on simtk.org), but ran into problems trying to run the AMD benchmarks.  When I updated my driver, OpenCL stopped being able to see my GPU. :(  I just need to spend some time debugging it.

I don't have access to an Ampere card.  If someone does, those would be good benchmarks to add.

**Comment by peastman** [comment]
This was done long ago.
